gameplus/mysit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic import RedirectView
from game.views import *
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^$',user_login),
    url(r'^login/$',user_login),
    url(r'^logo/$', logo_login),
    url(r'^login/forgetpassword/$',forget_password),
    url(r'^login/resetpassword/(.*)/$',set_new_password),
    url(r'^category/(.*)/$',category),
    url(r'^activate/(.*)/$',active_user),
    url(r'^account/password/(.*)/$',set_new_password),
    url(r'^accountManager/$',management),
    url(r'^search/$',search_game),
    url(r'^contact/$',contact),
    url(r'^(.*)/usergame/$',usergame),
    url(r'^usergame/$',usergame),
    url(r'^pay/(.*)/$', payment),
    url(r'^play/(.*)/$', play, name='play'),
    url(r'^edit/(.*)/$', game_edit),
    url(r'^payment/(.*)/?.*/$',payment_success),
    url(r'^gameInfo/(.*)/$', gameInfo),
    url(r'^mygame/$',TemplateView.as_view(template_name='mygame.html'))
]

gameplus/game/models.py
# Create your models here.
from __future__ import unicode_literals
import PIL
from django.db import models
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
fs = FileSystemStorage(location='/media')
# Create your models here.
class UserProfile(models.Model):
    user_category=models.CharField(max_length=2,default=2)
    user_image=models.CharField(max_length=150,blank=True,null=True)
    user_valid = models.BooleanField(default=False)
    user_dev_games=models.CharField(max_length=500,default='/',blank=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE)



class Game(models.Model):
    game_id=models.AutoField(primary_key=True)
    game_name=models.CharField(max_length=255)
    game_category=models.CharField(max_length=20)
    game_price=models.DecimalField(max_digits=10,decimal_places=2)
    game_date=models.DateField(blank=True)
    game_description=models.CharField(max_length=255)
    game_sale=models.IntegerField(max_length=10,default=0)
    game_pic=models.ImageField(storage=fs,blank=True,null=True)
    game_path=models.CharField(max_length=150,blank=True,null=True)
    player=models.ManyToManyField(User,blank=True,null=True)
    #developer=models.ForeignKey(User,blank=True,null=True)



class Score(models.Model):
    score_id=models.AutoField(primary_key=True)
    score=models.CharField(max_length=255)
    save_score=models.CharField(max_length=255,blank=True,null=True)
    player=models.ForeignKey(User)
    game=models.ForeignKey(Game)

gameplus/templates/HomePage.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Game +</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Bootstrap libraries-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!-- Custom CSS -->
  <link rel="stylesheet" type="text/css" href="css/main.css">
</head>

<body>
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>                        
        </button>
		<a class="navbar-brand" href="#">
			<img id="logo" src="img/logo.png" alt="Logo">
		</a>
    </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav navbar-left">
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Category<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Dice</a></li>
          <li><a href="#">Sports</a></li>
		  <li><a href="#">Music</a></li>
		  <li><a href="#">Others</a></li>
        </ul>
      </li>
      <li><a href="#">My Game</a></li>
	  <li><a href="#">Contact</a></li>
    </ul>
	<form class="navbar-form navbar-right">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </div>
      </div>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> xxxx</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Log out</a></li>
    </ul>
    </div>
  </div>
</nav>
  
<!-- Page Content -->
<div id="container" class="container">
	<div class="row">
    <div class="col-md-12">
		<h3>New Games</h3>
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			<!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
			<!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img id="carousel" class="slide-image" src="http://placehold.it/800x300" alt="">
                </div>
                <div class="item">
                    <img id="carousel" class="slide-image" src="http://placehold.it/800x300" alt="">
                </div>
                <div class="item">
                    <img id="carousel" class="slide-image" src="http://placehold.it/800x300" alt="">
                </div>
            </div>
			<!-- Left and right controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
            </a>
        </div>
	</div>
	</div>
	
    <div class="row">
	<div class="col-md-12">
	<h3><a id="category" href="#">Action</a></h3>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div>
		<div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div> 
	</div>
	<div class="col-md-12">
	<h3><a id="category" href="#">Dice</a></h3>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div>
		<div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div> 
	</div>
		<div class="col-md-12">
	<h3><a id="category" href="#">Sports</a></h3>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div>
		<div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div> 
	</div>
		<div class="col-md-12">
	<h3><a id="category" href="#">Music</a></h3>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div>
		<div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div> 
	</div>
		<div class="col-md-12">
	<h3><a id="category" href="#">Others</a></h3>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div>
		<div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/320x150" alt="">
                <div class="caption">
					<h4 class="pull-right">$price</h4>
					<h4><a href="#">Product Name</a></h4>
					<p>Some description here</p>
                </div>
            </div>
        </div> 
	</div>
    </div>
</div>

<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy; Game + 2016</p>
        </div>
    </div>
</footer>

</body>
</html>

gameplus/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Game +</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Bootstrap libraries-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!-- Custom CSS -->
  <link rel="stylesheet" type="text/css" href="/static/css/main.css">
  <!-- Custom js -->
<!-- Custom game read save load js -->
<script type="text/javascript" src="/static/js/playgame.js"></script>

  <script type="text/javascript">
  <!-- Image preview -->
	function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

                reader.onload = function (e) {
                    $('#preview')
                        .attr('src', e.target.result)
                        .width(150)
                        .height(150);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
   <!-- Confirm popup -->
	function show_confirm() {
		var r=confirm("Are you sure you want to remove this game!");
		if (r==true)
		{
      document.getElementById('remove').value='is_remove';
			return true;
		}
		else
		{
      document.getElementById('remove').value='not_remove';
			return false;
		}
	}
	</script>
</head>

<body>
{% block mainbody %}

{% endblock %}
</body>
</html>

gameplus/templates/category.html
{% extends "base.html" %}

{% block mainbody %}
<!-- navigation -->
{% include 'nav.html' %}
<!-- Category Content -->
<div id="container" class="container">
    <div class="row">
	<div class="col-md-12">
		<h3><a id="category" href="#">{{cate}}</a></h3>
		{% for game in games %}
			<div class="col-sm-4 col-lg-4 col-md-4">
				<div class="thumbnail">
					<img src="/static/pic/what.jpeg" alt="">
					<div class="caption">
						<h4 class="pull-right">${{game.game_price}}</h4>
						<h4><a href="/gameInfo/{{game.game_name}}">{{game.game_name}}</a></h4>
						<p>{{games.description}}</p>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
    </div>
</div>
<!-- footer -->
{% include 'footer.html' %}
{% endblock %}

</body>
</html>

gameplus/templates/contact.html
{% extends "base.html" %}

{% block mainbody %}
<!-- navigation -->
{% include 'nav.html' %}
<!-- Contact Content -->
<div id="container" class="container">
	<div class="row">
		<div class="col-md-12">
			<h3>Contact</a></h3>
		<div class="col-md-8">
            <div class="well well-sm">
                <form>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" placeholder="Enter name" required="required" />
                        </div>
                        <div class="form-group">
                            <label for="email">Email Address</label>
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
                                <input type="email" class="form-control" id="email" placeholder="Enter email" required="required" /></div>
                        </div>
                        <div class="form-group">
                            <label for="subject">Subject</label>
                            <select id="subject" name="subject" class="form-control" required="required">
                                <option value="na" selected="">Choose One:</option>
                                <option value="service">General Customer Service</option>
                                <option value="suggestions">Suggestions</option>
                                <option value="product">Product Support</option>
								<option value="payment">Payment Issue</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">Message</label>
                            <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required" placeholder="Message"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary pull-right" id="btnContactUs">Send Message</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <form>
            <legend><span class="glyphicon glyphicon-globe"></span>Our office</legend>
            <address>
                <strong>Game+ Oy.</strong><br>
               	Otaranta 6, Otaniemi<br>
                Espoo, Finland<br>
                <abbr title="Phone">Phone:</abbr>(+358) 469-679468
            </address>
            <address>
                <strong>Contact Email</strong><br>
                <a href="mailto:#">support@gameplus.com </a>
            </address>
            </form>
        </div>

	</div>
</div>
<!-- footer -->
{% include 'footer.html' %}
{% endblock %}

</body>
</html>

gameplus/templates/developerGame.html
<!-- List all games which the developer upload and order by the name of game -->
{% for game in dev_games %}
<div class="col-sm-4 col-lg-4 col-md-4">
	<div class="thumbnail">
		<img src="/static/pic/what.jpeg" alt="">
		<div class="caption">
			<h4 class="pull-right">${{game.game_price}}</h4>
			<h4>{{game.game_name}}</h4>
			<p>{{game.game_description}}</p>
		</div>
		<form class="form-horizontal" role="form" method="post">{% csrf_token %}
			<div class="form-group">
				<input type="hidden" class="form-control" id="gameName" name="gameName" value="{{game.game_name}}">
			</div>
			<div class="form-group last">
			<div class="col-sm-offset-3 col-sm-9">
				<a href ="/edit/{{game.game_name}}/">edit</a>
				<!-- <button type="submit" class="btn btn-success btn-sm" id="edit" name="edit" value="edit" >Edit</button> -->
				<button type="submit" onclick="show_confirm()" class="btn btn-default btn-sm" id="remove" name="remove" value="remove" >Remove</button>
			</div>
			</div>
		</form>
	</div>

</div>
{% endfor %}

gameplus/templates/editGame.html
{% extends "base.html" %}

{% block mainbody %}
<!-- navigation -->
{% include 'nav.html' %}
<!-- List the select game which the developer want to edit-->
<div id="container" class="container">
	<div class="row">
		<div class="col-md-12">
		<h3>Edit Game<h3>
		<span style="color: red">{{ mess }}</span>
		<form class="form-horizontal" role="form"  method="post">{% csrf_token %}
			<div class="form-group">
				<label for="inputGame" class="col-sm-3 control-label">Game Name</label>
				<div class="col-sm-9">
					{{ game.game_name }}
				</div>
			</div>
			<div class="form-group">
				<label for="price" class="col-sm-3 control-label">Price</label>
				<div class="col-sm-9">
					<input type="number" class="form-control" name="price" placeholder="{{ game.game_price }}" required="required">
				</div>
			</div>
			<div class="form-group">
				<label for="description" class="col-sm-3 control-label">Description</label>
				<div class="col-sm-9">
					<textarea class="form-control" name="description" placeholder="{{ game.game_description }}" required="required"></textarea>
				</div>
			</div>
			<div class="form-group">
				<label for="catergory" class="col-sm-3 control-label">Category</label>
				<div class="col-sm-9">
					<select class="form-control custom-select" name="catergory" required="required">
						<option selected>{{game.game_category}}</option>
						{% for category in categories %}
						<option>{{ category }}</option>
						{% endfor %}
					</select>
				</div>
			</div>
			<div class="form-group">
				<label for="url" class="col-sm-3 control-label">URL</label>
				<div class="col-sm-9">
					<input type="url" class="form-control" name="url" placeholder="{{ game.game_path }}" required="required">
				</div>
			</div>
			<div class="form-group">
				<label for="uploadedimage" class="col-sm-3 control-label custom-file">Uploaded Image</label>
				<div class="col-sm-9">
					<input type='hidden' name='uploadedimage' value="{{game.game_pic}}" />
					<img id="uploadedimage" src="{{game.game_pic}}" alt=""/>
				</div>
			</div>
			<div class="form-group">
				<label for="image" class="col-sm-3 control-label custom-file">Image</label>
				<div class="col-sm-9">
					<input type='hidden' name='MAX_FILE_SIZE' value='2000000' />
					<input type="file" class="file" name="image" onchange="readURL(this);">
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label custom-file">Image Preview</label>
				<div class="col-sm-9">
					<img id="preview" src="#" alt="You not upload image yet"/>
				</div>
			</div>
			<div class="form-group last">
				<div class="col-sm-offset-3 col-sm-9">
					<button type="submit" class="btn btn-success btn-sm">Save Change</button>
				</div>
			</div>
		</form>
        </div>
	</div>
</div>

<!-- footer -->
{% include 'footer.html' %}
{% endblock %}

</body>
</html>

gameplus/templates/gamedescription.html
{% extends "base.html" %}

{% block mainbody %}
<!-- navigation -->
{% include 'nav.html' %}
<!-- Play Game Content -->
{% load staticfiles %}
<div id="container" class="container">
    <div class="row">
	<div class="col-md-12">
		<div class="thumbnail">
			<img class="img-responsive" src="/static/pic/what.jpeg" alt="">
			<div class="caption-full">
				<h4 class="pull-right">${{game.game_price}}</h4>
				<h4>{{game.game_name}}</h4>
				{% if user in all_players  %}
				<a href="/play/{{game.game_name}}" class="btn btn-primary btn-sm pull-right" role="button">Play</a>
				{% else %}
				<a href="/pay/{{game.game_name}}" class="btn btn-primary btn-sm pull-right" role="button">Buy</a>
				{% endif %}
				<p>{{game.game_description}}</p>
			</div>
		</div>
	</div>
    </div>
</div>
<!-- footer -->
{% include 'footer.html' %}
{% endblock %}

</body>
</html>

gameplus/templates/main.html
{% extends "base.html" %}


{% block mainbody %}
<!-- navigation -->
{% include 'nav.html' %}

<!-- Page Content -->
<div id="container" class="container">
	<div class="row">
    <div class="col-md-12">
		<h3>New Games</h3>
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			<!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
			<!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <a href="#"><img id="carousel" class="slide-image" src='/static/pic/dota.jpeg' alt=""></a>
                </div>
                <div class="item">
                    <a href="#"><img id="carousel" class="slide-image" src='/static/pic/what.jpeg' alt=""></a>
                </div>
                <div class="item">
                    <a href="#"><img id="carousel" class="slide-image" src='/static/pic/he.jpeg' alt=""></a>
            </div>
			<!-- Left and right controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
            </a>
        </div>
	</div>
	</div>
	</div>

    <div class="row">
	{% for category in categories %}
	<div class="col-md-12">
	<h3><a id="category" href=/category/{{category}}/>{{category}}</a></h3>
	{% for game in games %}
	{% if game.game_category == category  %}
	{% load staticfiles %}
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img src="/static/pic/what.jpeg" alt="game image">
                <div class="caption">
					<h4 class="pull-right">{{game.game_price}}</h4>
					<h4><a href="/gameInfo/{{game.game_name}}">{{game.game_name}}</a></h4>
					<p>{{game.game_description}}</p>
                </div>
            </div>
        </div>
	{% endif %}
	{% endfor %}
	</div>
	{% endfor %}
    </div>

</div>
<!-- footer -->
{% include 'footer.html' %}
{% endblock %}

</body>
</html>

gameplus/templates/playgame.html
{% extends "base.html" %}

{% block mainbody %}
<!-- navigation -->
{% include 'nav.html' %}
<!-- Play Game Content -->

<div id="container" class="container">
	<!-- Game name as Heading -->
    <div class="row">
		<div class="col-md-12">
			<h1 class="page-header">Play Name</h1>
		</div>
	</div>
	<!-- End Heading -->
	<div class="row">
		<!-- Play Game Window -->
		<div class="col-sm-8 col-md-8 col-lg-8 embed-responsive embed-responsive-16by9">
			<iframe class="col-md-12 embed-responsive-item" width="100%" height="100%" src="/mygame"></iframe>
		</div>
		<!-- Game Information -->
		<div class="col-md-4">

      <h5 id="error_message"></h5>
      <form method="post" id="play_form">
                          {% csrf_token %}
      					<div class="form-group">
      						<input type="hidden" class="form-control" name="score" id="id_score" required="required">
      					</div>
      </form>


                <h3>High Score</h3>
                <h3 class="section-title">Last Round Score: <span id="last_round">0</span></h3>
				<div class="table-responsive">

					<table class="table">
					<tbody>
					{% if max_score_wrap %}
						<tr>
						<td>{{max_score_wrap.player.user_name}}</td>
						<td>{{max_score_wrap.score}}</td>

						</tr>
					{% else %}
						<tr>
						No record
						</tr>
					{% endif %}
					</tbody>
					</table>
				</div>
        {{error}}
				<h3>Your Best Score</h3>

				<p>{% if yourscore %}
					{{yourscore.score}}
					{% else %}
					No record
					{% endif %}</p>
				<h3>Share In Social Media</h3>
				<a href="http://twitter.com/share?url=<SITE>&text=<TITLE>@<TAG>"></a>
        {% load social_share %}
        {% post_to_facebook  www.game_name.com "Post to Facebook!" %}
        {% post_to_twitter "Good Game: {{game.game_name}}. {{game.game_pic}} Check it out!" game.game_path "Post to Twitter"  %}
            </div>
	</div>

</div>

<!-- footer -->
{% include 'footer.html' %}
{% endblock %}

</body>
</html>